// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAoZ9NKn8cO4bjifUQl09-l5tjFOv2Wpk',
    appId: '1:1047875439292:web:c8bbe46cb5ea2b3685deb9',
    messagingSenderId: '1047875439292',
    projectId: 'midsem-auth-app',
    authDomain: 'midsem-auth-app.firebaseapp.com',
    storageBucket: 'midsem-auth-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMRQR9i90jgcWshK4HtvxhPEZhHxhWuGY',
    appId: '1:1047875439292:android:047163710cf335eb85deb9',
    messagingSenderId: '1047875439292',
    projectId: 'midsem-auth-app',
    storageBucket: 'midsem-auth-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjUFkxhNvjsrXDgQpVU7WfUPcqnh_JZH4',
    appId: '1:1047875439292:ios:0c7b70f7be4bea5f85deb9',
    messagingSenderId: '1047875439292',
    projectId: 'midsem-auth-app',
    storageBucket: 'midsem-auth-app.firebasestorage.app',
    iosBundleId: 'com.example.midsemExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjUFkxhNvjsrXDgQpVU7WfUPcqnh_JZH4',
    appId: '1:1047875439292:ios:0c7b70f7be4bea5f85deb9',
    messagingSenderId: '1047875439292',
    projectId: 'midsem-auth-app',
    storageBucket: 'midsem-auth-app.firebasestorage.app',
    iosBundleId: 'com.example.midsemExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAoZ9NKn8cO4bjifUQl09-l5tjFOv2Wpk',
    appId: '1:1047875439292:web:c94bcad06aeccf7d85deb9',
    messagingSenderId: '1047875439292',
    projectId: 'midsem-auth-app',
    authDomain: 'midsem-auth-app.firebaseapp.com',
    storageBucket: 'midsem-auth-app.firebasestorage.app',
  );
}
